# Generated by Django 4.1.1 on 2022-10-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_webApp', '0002_list_created_date_list_description_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
