# Generated by Django 4.1.1 on 2022-10-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_webApp', '0003_alter_list_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
