# Generated by Django 4.1.1 on 2022-10-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_webApp', '0004_list_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='published_date',
        ),
    ]
