# Generated by Django 4.1.1 on 2022-10-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_webApp', '0005_remove_list_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
