# Generated by Django 4.1.1 on 2022-10-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_webApp', '0006_alter_list_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartAapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('room_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
