# Generated by Django 4.1.1 on 2022-10-24 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_webApp', '0009_alter_room_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 24, 12, 21, 29, 236751, tzinfo=datetime.timezone.utc)),
        ),
    ]
